services:
  - type: web
    name: dataniaga-api
    runtime: python311
    startCommand: cd api && gunicorn -w 4 -k uvicorn.workers.UvicornWorker index:app
    buildCommand: pip install -r requirements.txt && pip install gunicorn
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
